/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thi_csdlpt;

import java.io.File;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROYCE SHEW
 */
public class GIAODIENCHINH extends javax.swing.JFrame {

    private DefaultTableModel tblmodel;

    /**
     * Creates new form GIAODIENCHINH
     */
    public GIAODIENCHINH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MANH1_SANPHAM = new javax.swing.JButton();
        MANH2_SANPHAM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        KHACHHANG_MANH1 = new javax.swing.JButton();
        KHACHHANG_MANH2 = new javax.swing.JButton();
        KHOHANG_MANH1 = new javax.swing.JButton();
        KHOHANG_MANH2 = new javax.swing.JButton();
        HOADON_MANH1 = new javax.swing.JButton();
        HOADON_MANH2 = new javax.swing.JButton();
        CHITIETHOADON_MANH1 = new javax.swing.JButton();
        CHITIETHOADON_MANH2 = new javax.swing.JButton();
        SANPHAM = new javax.swing.JButton();
        KHACHHANG = new javax.swing.JButton();
        KHOHANG = new javax.swing.JButton();
        HOADON = new javax.swing.JButton();
        CHITIETHOADON = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MANH1_SANPHAM.setText("MANH1");
        MANH1_SANPHAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MANH1_SANPHAMActionPerformed(evt);
            }
        });

        MANH2_SANPHAM.setText("MANH2");
        MANH2_SANPHAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MANH2_SANPHAMActionPerformed(evt);
            }
        });

        jLabel1.setText("MANH");

        KHACHHANG_MANH1.setText("MANH1");
        KHACHHANG_MANH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KHACHHANG_MANH1ActionPerformed(evt);
            }
        });

        KHACHHANG_MANH2.setText("MANH2");
        KHACHHANG_MANH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KHACHHANG_MANH2ActionPerformed(evt);
            }
        });

        KHOHANG_MANH1.setText("MANH1");
        KHOHANG_MANH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KHOHANG_MANH1ActionPerformed(evt);
            }
        });

        KHOHANG_MANH2.setText("MANH2");
        KHOHANG_MANH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KHOHANG_MANH2ActionPerformed(evt);
            }
        });

        HOADON_MANH1.setText("MANH1");
        HOADON_MANH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOADON_MANH1ActionPerformed(evt);
            }
        });

        HOADON_MANH2.setText("MANH2");
        HOADON_MANH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOADON_MANH2ActionPerformed(evt);
            }
        });

        CHITIETHOADON_MANH1.setText("MANH1");
        CHITIETHOADON_MANH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHITIETHOADON_MANH1ActionPerformed(evt);
            }
        });

        CHITIETHOADON_MANH2.setText("MANH2");
        CHITIETHOADON_MANH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHITIETHOADON_MANH2ActionPerformed(evt);
            }
        });

        SANPHAM.setText("SANPHAM");
        SANPHAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SANPHAMActionPerformed(evt);
            }
        });

        KHACHHANG.setText("KHACHHANG");
        KHACHHANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KHACHHANGActionPerformed(evt);
            }
        });

        KHOHANG.setText("KHOHANG");
        KHOHANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KHOHANGActionPerformed(evt);
            }
        });

        HOADON.setText("HOADON");
        HOADON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOADONActionPerformed(evt);
            }
        });

        CHITIETHOADON.setText("CHITIETHOADON");
        CHITIETHOADON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHITIETHOADONActionPerformed(evt);
            }
        });

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane2.setViewportView(txtError);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KHOHANG_MANH1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(KHOHANG_MANH2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(KHOHANG))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MANH1_SANPHAM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(MANH2_SANPHAM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SANPHAM))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(KHACHHANG_MANH1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(KHACHHANG_MANH2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(KHACHHANG)))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CHITIETHOADON_MANH1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CHITIETHOADON_MANH2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CHITIETHOADON))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(HOADON_MANH1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HOADON_MANH2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HOADON)))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MANH1_SANPHAM)
                    .addComponent(MANH2_SANPHAM)
                    .addComponent(jLabel1)
                    .addComponent(SANPHAM)
                    .addComponent(HOADON_MANH1)
                    .addComponent(HOADON_MANH2)
                    .addComponent(HOADON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KHACHHANG_MANH1)
                    .addComponent(KHACHHANG_MANH2)
                    .addComponent(KHACHHANG)
                    .addComponent(CHITIETHOADON_MANH1)
                    .addComponent(CHITIETHOADON_MANH2)
                    .addComponent(CHITIETHOADON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KHOHANG_MANH1)
                    .addComponent(KHOHANG_MANH2)
                    .addComponent(KHOHANG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MANH1_SANPHAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MANH1_SANPHAMActionPerformed
        // TODO add your handling code here:
        File f = new File("D:/sanpham_1.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma San Pham","Ten San Pham"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataSanPhamManh(f, tblmodel, tblResult, txtError, tenCot, "1" );

    }//GEN-LAST:event_MANH1_SANPHAMActionPerformed

    private void MANH2_SANPHAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MANH2_SANPHAMActionPerformed
        // TODO add your handling code here: File f = new File("D:/sanpham_2.txt");
        File f = new File("D:/sanpham_2.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma San Pham","Gia Ban","Ma Kho"} ;
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataSanPhamManh(f, tblmodel, tblResult, txtError, tenCot, "2" );
    }//GEN-LAST:event_MANH2_SANPHAMActionPerformed

    private void SANPHAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SANPHAMActionPerformed
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[]={"Ma San Pham","Ten San Pham","Gia Ban","Ma Kho"};
        File f = new File("D:/sanpham_1.txt");
        ArrayList<ArrayList<String>> a = db.getManhSanPham(f, tblmodel, tblResult, txtError, tenCot,"1");
        f = new File("D:/sanpham_2.txt");
        ArrayList<ArrayList<String>> b = db.getManhSanPham(f, tblmodel, tblResult, txtError, tenCot,"2");
        ArrayList<ArrayList<String>> c = db.ket(a, b);
        tblmodel = db.getTableModel(tenCot, c);
        tblResult.setModel(tblmodel);
    }//GEN-LAST:event_SANPHAMActionPerformed

    private void KHACHHANG_MANH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KHACHHANG_MANH1ActionPerformed
        // TODO add your handling code here:
        File f = new File("D:/sanpham_1.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Khach Hang", "Ten Khach Hang", "Loai Khach Hang"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataKhachHangManh(f, tblmodel, tblResult, txtError, tenCot, "1" );
    }//GEN-LAST:event_KHACHHANG_MANH1ActionPerformed

    private void KHACHHANG_MANH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KHACHHANG_MANH2ActionPerformed
        // TODO add your handling code here:
        File f = new File("D:/sanpham_2.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Khach Hang", "Dia Chi", "So Dien Thoai"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataKhachHangManh(f, tblmodel, tblResult, txtError, tenCot, "2" );
    }//GEN-LAST:event_KHACHHANG_MANH2ActionPerformed

    private void KHACHHANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KHACHHANGActionPerformed
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[]={"Ma Khach Hang","Ten Khach Hang", "Dia Chi", "So Dien Thoai", "Loai Khach Hang"};
        File f = new File("D:/sanpham_1.txt");
        ArrayList<ArrayList<String>> a = db.getManhKhachHang(f, tblmodel, tblResult, txtError, tenCot,"1");
        f = new File("D:/sanpham_2.txt");
        ArrayList<ArrayList<String>> b = db.getManhKhachHang(f, tblmodel, tblResult, txtError, tenCot,"2");
        ArrayList<ArrayList<String>> c = db.ket(a, b);
        tblmodel = db.getTableModel(tenCot, c);
        tblResult.setModel(tblmodel);
    }//GEN-LAST:event_KHACHHANGActionPerformed

    private void KHOHANG_MANH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KHOHANG_MANH1ActionPerformed
        // TODO add your handling code here:
        File f = new File("D:/sanpham_1.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Kho Hang", "Ten Kho Hang"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataKhoHangManh(f, tblmodel, tblResult, txtError, tenCot, "1" );
    }//GEN-LAST:event_KHOHANG_MANH1ActionPerformed

    private void KHOHANG_MANH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KHOHANG_MANH2ActionPerformed
        // TODO add your handling code here:
        File f = new File("D:/sanpham_2.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Kho Hang", "Dia Chi"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataKhoHangManh(f, tblmodel, tblResult, txtError, tenCot, "2" );
    }//GEN-LAST:event_KHOHANG_MANH2ActionPerformed

    private void KHOHANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KHOHANGActionPerformed
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[]={"Ma Kho Hang","Ten Kho Hang", "Dia Chi"};
        File f = new File("D:/sanpham_1.txt");
        ArrayList<ArrayList<String>> a = db.getManhKhoHang(f, tblmodel, tblResult, txtError, tenCot,"1");
        f = new File("D:/sanpham_2.txt");
        ArrayList<ArrayList<String>> b = db.getManhKhoHang(f, tblmodel, tblResult, txtError, tenCot,"2");
        ArrayList<ArrayList<String>> c = db.ket(a, b);
        tblmodel = db.getTableModel(tenCot, c);
        tblResult.setModel(tblmodel);
    }//GEN-LAST:event_KHOHANGActionPerformed

    private void HOADON_MANH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOADON_MANH1ActionPerformed
        // TODO add your handling code here:
        File f = new File("D:/sanpham_1.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Hoa Don", "Ma Khach Hang", "Ngay"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "1" );
    }//GEN-LAST:event_HOADON_MANH1ActionPerformed

    private void HOADON_MANH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOADON_MANH2ActionPerformed
        // TODO add your handling code here:
        File f = new File("D:/sanpham_2.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Hoa Don", "Ma Khach Hang", "Ngay"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "2" );
    }//GEN-LAST:event_HOADON_MANH2ActionPerformed

    private void HOADONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOADONActionPerformed
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Hoa Don", "Ma Khach Hang", "Ngay"};
        tblmodel = new DefaultTableModel(tenCot,0);
        File f = new File("D:/sanpham_1.txt");
        db.getDataHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "1");
        f = new File("D:/sanpham_2.txt");
        db.getDataHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "2"); 
    }//GEN-LAST:event_HOADONActionPerformed

    private void CHITIETHOADON_MANH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHITIETHOADON_MANH1ActionPerformed
        // TODO add your handling code here:
        File f = new File("D:/sanpham_1.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Hoa Don", "Ma San Pham", "So Luong"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataChiTietHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "1" );
    }//GEN-LAST:event_CHITIETHOADON_MANH1ActionPerformed

    private void CHITIETHOADON_MANH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHITIETHOADON_MANH2ActionPerformed
        // TODO add your handling code here:
        File f = new File("D:/sanpham_2.txt");
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Hoa Don", "Ma San Pham", "So Luong"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataChiTietHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "2" );
    }//GEN-LAST:event_CHITIETHOADON_MANH2ActionPerformed

    private void CHITIETHOADONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHITIETHOADONActionPerformed
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[]= {"Ma Hoa Don", "Ma San Pham", "So Luong"};
        tblmodel = new DefaultTableModel(tenCot,0);
        File f = new File("D:/sanpham_1.txt");
        db.getDataChiTietHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "1");
        f = new File("D:/sanpham_2.txt");
        db.getDataChiTietHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "2"); 
    }//GEN-LAST:event_CHITIETHOADONActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHITIETHOADON;
    private javax.swing.JButton CHITIETHOADON_MANH1;
    private javax.swing.JButton CHITIETHOADON_MANH2;
    private javax.swing.JButton HOADON;
    private javax.swing.JButton HOADON_MANH1;
    private javax.swing.JButton HOADON_MANH2;
    private javax.swing.JButton KHACHHANG;
    private javax.swing.JButton KHACHHANG_MANH1;
    private javax.swing.JButton KHACHHANG_MANH2;
    private javax.swing.JButton KHOHANG;
    private javax.swing.JButton KHOHANG_MANH1;
    private javax.swing.JButton KHOHANG_MANH2;
    private javax.swing.JButton MANH1_SANPHAM;
    private javax.swing.JButton MANH2_SANPHAM;
    private javax.swing.JButton SANPHAM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextArea txtError;
    // End of variables declaration//GEN-END:variables
}
